#!/usr/bin/env bash

# To display line numbers when debugging
PS4='${LINENO}: '

ARCHIVE_NAME="logs_archive_$(date +%Y%d%m_%H%M%S).tar.gz"
TARGET_DIRECTORY=""
TARGET_PATH=""
HERE=false

# Help function
show_help() {
	cat << EOF
Usage: $0 [-p|--path] <target_archive_directory> [--here] <target_directory> [-h|--help]

Options:
  OPTION       DESCRIPTION
  -h, --help   Show this help message and exit
  -p, --path   To specify the path of the archive directory
      --here   To archive in the current working directory

Examples:
	./log-archive --here <target_directory>
	./log-archive -p /path/to/destination <target_directory>
EOF
echo
}

# Error function
error_exit() {
	echo "Error: $1"
	echo "Use './log-archive --help' for more information."
	exit 1
}

if [[ $# -eq 0 ]]; then
	show_help
	exit 1
fi

# Archive function
archive() {
	local target_path=$1
	local target_directory=$2

	# If empty target path
	if [[ -z "$target_path" ]]; then
		if tar -czf "$ARCHIVE_NAME" "$target_directory"; then
			echo "Archived $ARCHIVE_NAME in this current directory"
		fi
	fi

	# If target path is not empty and is writable
	if [[ -n "$target_path" ]] && [[ -w "$target_path" ]]; then
		if tar -czf "${target_path}/$ARCHIVE_NAME" "$target_directory"; then
			echo "Archived $ARCHIVE_NAME in path '$target_path'"
		fi
	else
		error_exit "Destination $target_path is not writable"
	fi
}

# Parsing arguments
while [[ $# -gt 0 ]];
do
	case "$1" in
		-h | --help)
			show_help
			exit 0
			;;

		-p | --path)
			if [ "$2" ]; then
				TARGET_PATH=$2
				shift 2
				break
			else
				error_exit "-p|--path requires a /path/to/destination"
			fi
			;;

		--here)
			HERE=true
			TARGET_PATH=$(pwd)
			shift
			break
			;;

		*)
			error_exit "Unknown option: $1"
			;;
	esac
	shift
done

# If target directory is not provided
if [[ $# -ne 1 ]]; then
	error_exit "Missing target directory"
fi
TARGET_DIRECTORY=$1

# If target directory does not exist
if [[ ! -d "$TARGET_DIRECTORY" ]]; then
	error_exit "'$TARGET_DIRECTORY' does not exist."
fi

# Archive target directory to target path
archive "$TARGET_PATH" "$TARGET_DIRECTORY"
